Broadcast execution completed
trento-project/web pull request #1023
Opened 2022-12-01 15:23 UTC by fabriziosestito

Adds the updated execution completed action dispatch when the BE receives an execution completed event from wanda.

NOTE:
I had to add the channel and the callback manually and couldn't rely on the `registerEvents` utility function since the name of the action and the message sent to the phoenix channel differs.
Also, I'd like to use action constants instead of generating  the name of the action so I will track a debt to track an improvement on this side.

2022-12-01 15:26 UTC, dottorblaster requested changes
Just a tiny thing then we can merge

2022-12-01 15:26 UTC, dottorblaster commented on assets/js/state/index.js
> +  });
```suggestion
  channel.on('execution_completed', ({ group_id: groupID }) => {
    store.dispatch({
      type: UPDATE_LAST_EXECUTION,
      payload: { groupID },
    });
  });
```

2022-12-01 16:20 UTC, arbulu89 approved these changes
Looks good @fabriziosestito ,
Let's use the action function instead of importing the action key and creating the payload manually

2022-12-01 16:20 UTC, arbulu89 commented on assets/js/state/index.js
> +    store.dispatch({
We should import and use the appropriate action here: 
https://github.com/trento-project/web/blob/main/assets/js/state/actions/lastExecutions.js#L3
```
store.dispatch(updateLastExecution(groupID))
```

2022-12-02 07:10 UTC, arbulu89 approved these changes

2022-12-02 08:11 UTC, dottorblaster approved these changes
LGTM

2022-12-02 09:48 UTC, merged