Remove legacy runner events
trento-project/web pull request #1170
Opened 2023-02-06 13:42 UTC by arbulu89

# Description

Remove legacy events usage and code around it like unused read models and their database configuration.
The legacy events are moved to a `legacy` folder, because they must exist in the code, as they are part of the stream, but they don't apply any change to the aggregate anymore

## How was this tested?

Mostly test were removed. A new single test to check the legacy events don't change the aggregate was added

2023-02-07 08:13 UTC, arbulu89 commented on lib/trento/domain/cluster/cluster.ex
> +  def apply(cluster, %legacy_event{}) when legacy_event in @legacy_events, do: cluster
This is the unique new piece of code

2023-02-07 15:48 UTC, nelsonkopliku approved these changes
![image](https://user-images.githubusercontent.com/8167114/217292480-e3cba96d-18db-4d04-af75-08e28f3fe4fb.png)

2023-02-07 18:07 UTC, fabriziosestito requested changes
We need also to clean up `TrentoWeb.OpenApi.Schema.Cluster`, mega LGTM for the rest.

2023-02-08 07:56 UTC, arbulu89 commented
> We need also to clean up `TrentoWeb.OpenApi.Schema.Cluster`, mega LGTM for the rest.

Thanks @fabriziosestito good catch.
Updated

2023-02-08 08:33 UTC, dottorblaster approved these changes
LGTM

2023-02-08 15:12 UTC, merged