Check Result Detail pt2
trento-project/web pull request #1264
Opened 2023-03-17 10:21 UTC by nelsonkopliku

# Description

This PR introduces the detailed information about the execution of a specific check on a target (only expect statements on a target of type host)

Successful (passing/failing)

![check-detail-success](https://user-images.githubusercontent.com/8167114/227246666-ef83a23c-6662-4849-8d50-765e9a57ba7d.gif)

Check error/Agent timeout

![check-detail-error-and-timeout](https://user-images.githubusercontent.com/8167114/227246696-8ff65043-6e7f-4f3a-b1b0-11d0ac5a91bc.gif)

What's next:

- detailed visualization for a cluster wide check (expect_same statements)
- add a result icon in the title as per figma mockup
- improve facts visualization for scalar values (should support plain strings/numbers/booleans besides lists/objects)
- improve detail page title (markdown ?)
- improve `<ListView />` component to allow custom spacing (to reduce the distance between expectations, values and fact names from the respective value )
- improve URL edge cases (what happens if a detail for a wrong checkID/targetType/targetName was requested? probably an error)
- cleanup legacy code

Going to create items in the backlog

## How was this tested?
Automated tests.

2023-03-27 15:35 UTC, dottorblaster requested changes
Nice! Little things to adjust :+1:

2023-03-27 15:35 UTC, dottorblaster commented on assets/js/components/ExecutionResults/CheckResultDetail/CheckResultDetail.jsx
> +      <GatheredFacts gatheredFacts={facts || []} />
You don't need this `||` since you used a default in the upper statement

2023-03-27 15:35 UTC, dottorblaster commented on assets/js/components/ExecutionResults/CheckResultDetail/CheckResultDetail.jsx
> +        isCheckError={isCheckError}
Maybe `isError` would be just enough?

2023-03-27 15:35 UTC, dottorblaster commented on assets/js/components/ExecutionResults/CheckResultDetail/CheckResultDetail.jsx
> +        isCheckError={isCheckError}
(or just `error`)

2023-03-27 15:35 UTC, dottorblaster commented on assets/js/components/ExecutionResults/CheckResultDetail/CheckResultDetail.jsx
> +        expectStatementsResults={expectStatementsResults}
```suggestion
        results={expectStatementsResults}
```

2023-03-27 15:35 UTC, dottorblaster commented on assets/js/components/ExecutionResults/CheckResultDetail/CheckResultDetail.jsx
> +      <ExpectedValues isCheckError={isCheckError} expectedValues={values} />
```suggestion
      <ExpectedValues isError={isCheckError} expectedValues={values} />
```

2023-03-27 15:35 UTC, dottorblaster commented on assets/js/components/ExecutionResults/CheckResultDetail/CheckResultDetailPage.jsx
> +    : clusterID;
I think this could be easily refactored using lodash, too bad we still don't have lodash

2023-03-27 15:35 UTC, dottorblaster commented on assets/js/components/ExecutionResults/CheckResultDetail/GatheredFacts.jsx
> +import ObjectTree from '@components/ObjectTree/ObjectTree';
```suggestion
import ObjectTree from '@components/ObjectTree';
```

2023-03-27 15:35 UTC, dottorblaster commented on assets/js/components/ExecutionResults/CheckResultDetail/GatheredFacts.jsx
> +        ),
```suggestion
      render: (factValue = {}) =>
        isFactError ? (
          <span className="text-red-500">{message}</span>
        ) : (
          <ObjectTree className="mt-3" data={factValue} />
        ),
```

I'm a bit fried at the moment, but would this work?

2023-03-28 07:37 UTC, dottorblaster commented on assets/js/components/ExecutionResults/CheckResultDetail/CheckResultDetail.jsx
> +      <GatheredFacts gatheredFacts={facts || []} />
RIP

2023-03-28 08:09 UTC, arbulu89 reviewed
Hey @nelsonkopliku ,
The code looks great!
I mentioned some annoying naming things mostly, but besides that I generally like it

2023-03-28 08:09 UTC, arbulu89 commented on assets/js/components/ExecutionResults/CheckResultDetail/CheckResultDetail.jsx
> +  const expectStatementsResults = getExpectStatements(expectation_evaluations);
Let's not use `Results` and use `Evaluation` to match with our code

2023-03-28 08:09 UTC, arbulu89 commented on assets/js/components/ExecutionResults/checksUtils.js
> +export const getExpectStatements = (expectationList) =>
I know that it is a bit redundant, but I would go with `getExpectExpectations`. 
This `Statement` word is coming like out of the blue (I know, already implemented in the prev PRs, but it striked me now)
Or maybe have `filterExpectationByType(type, expectationList)`

2023-03-28 08:13 UTC, nelsonkopliku commented on assets/js/lib/test-utils/factories/executions.js
> +  name: faker.lorem.word(),
Yes, that's exactly the issue :smile: changing to use sequence

2023-03-28 08:15 UTC, nelsonkopliku commented on assets/js/components/ExecutionResults/checksUtils.js
> +export const isTargetHost = (targetType) => targetType === TARGET_HOST;
I see, I will move them on top.
I was even thinking they can go somewhere in `lib/models`, but let's maybe agree together.

I am not sure I totally like what this checksUtils is becoming :sweat_smile:

2023-03-28 08:36 UTC, nelsonkopliku commented on assets/js/components/ExecutionResults/checksUtils.js
> +export const getCheckResultByAgentID = (executionData, checkID, agentID) => {
what about singularized? `getAgentCheckResultByAgentID`?

2023-03-28 08:53 UTC, arbulu89 approved these changes
Green light from my side

2023-03-28 08:53 UTC, arbulu89 commented on assets/js/components/ExecutionResults/checksUtils.js
> +export const getExpectStatements = (expectationList) =>
But we call them `expectations`, not `statements`. 
Anyhow, I'm fine with everyone else likes it

2023-03-29 08:39 UTC, jagabomb approved these changes
LGTM... I was going to mention a point about the spacing but I see you have already stated it in the description which I have referenced below. I'm excited to see the next set of improvements.

> improve <ListView /> component to allow custom spacing (to reduce the distance between expectations, values and fact names from the respective value )

2023-03-29 09:55 UTC, dottorblaster approved these changes
LGTM

2023-03-29 09:59 UTC, merged