Fix wrong filtered catalog being used in execution results page
trento-project/web pull request #1375
Opened 2023-05-03 15:03 UTC by nelsonkopliku

# Description

This PR fixes a bug where a previously filtered catalog state by a given provider is not what is needed in the execution results page where the cluster provider might differ from the provider used for the previous filtering in the catalog.

Example: filtering by GCP in the catalog loads a state that is not what is needed for the execution results of a cluster discovered on Azure.

This fix comes with a cost: landing on the execution results page triggers a refresh of the catalog.
Note that navigating from the execution results to the check detail does not retrigger the refresh, however navigating back from check detail to execution results does trigger a refresh.

![fix-catalog-loading-in-check-results](https://user-images.githubusercontent.com/8167114/236395247-89d21612-22a1-42c4-94be-862f30cca01a.gif)

## How was this tested?

Manually.

2023-05-09 09:03 UTC, dottorblaster requested changes
Just a tiny modification then we can merge :+1:

2023-05-09 09:03 UTC, dottorblaster commented on assets/js/components/ExecutionResults/ExecutionResultsPage.jsx
> +    if (cluster?.provider) {
Would you declare this like `const cloudProvider = cluster?.provider;` and just reference this instead of accessing two times the field?

2023-05-09 09:12 UTC, EMaksy reviewed
Besides @dottorblaster  comment, lgtm :D

2023-05-10 07:51 UTC, dottorblaster approved these changes
:shipit:

2023-05-10 07:52 UTC, merged