Add SAP System deregistration side effects
trento-project/web pull request #1387
Opened 2023-05-08 14:30 UTC by jamie-suse

# Description

This PR adds SAP System deregistration side effects.

Changes SAP System Projector: when `SapSystemDeregistered` event is received, update Read Model's `deregistered_at` field.

Updates Usecase `get_all_sap_systems()` to filter out deregistered SAP Systems.

## How was this tested?

Added unit tests for Projector and Usecase. Confirmed coverage of new changes via Coveralls.

2023-05-08 14:39 UTC, CDimonaco requested changes
Guys, the where condition is missing in lib/trento/application/usecases/sap_systems/health_summary_service.ex

On function `get_health_summary`

Please check for all the usage of SapSystemReadModel in associations or direct queries.

2023-05-08 14:42 UTC, CDimonaco commented on lib/trento/application/projectors/sap_system_projector.ex
> +    TrentoWeb.Endpoint.broadcast(
Maybe we could add a phoenix view?

2023-05-09 13:08 UTC, jamie-suse commented on lib/trento/application/projectors/sap_system_projector.ex
> +    TrentoWeb.Endpoint.broadcast(
Done! 🚀

2023-05-09 14:19 UTC, fabriziosestito requested changes
LGTM

Note: we are still missing the database part

2023-05-09 14:19 UTC, fabriziosestito approved these changes

2023-05-09 14:24 UTC, merged