Add software updates endpoints
trento-project/web pull request #2250
Opened 2024-02-01 13:05 UTC by jamie-suse

# Description

This change adds HTTP endpoints to allow reading/writing of credentials to the SAP software update system (i.e. at time of writing, SUSE Manager).

## How was this tested?

Added unit tests for new functions.

2024-02-02 13:29 UTC, nelsonkopliku requested changes
Awesome! A few comments though.

2024-02-02 13:29 UTC, nelsonkopliku commented on lib/trento_web/router.ex
> +      get "/user_settings", SoftwareUpdatesController, :get_user_settings
What about `/software-updates/settings`?

2024-02-02 13:29 UTC, nelsonkopliku commented on test/trento_web/views/v1/software_updates_view_test.exs
> +        insert(
I guess `build` would fit better than `insert`. No strict need to store anything in the database for this test? :eyes:

2024-02-02 13:29 UTC, nelsonkopliku commented on test/trento_web/views/v1/software_updates_view_test.exs
> +    test "should render all the fields" do
```suggestion
    test "should render relevant fields" do
```
Not really rendering _all_ the fields

2024-02-02 13:29 UTC, nelsonkopliku commented on test/trento_web/views/v1/software_updates_view_test.exs
> +      %Settings{url: url, username: username, ca_uploaded_at: ca_uploaded_at} =
```suggestion
      %Settings{url: url, username: username, ca_uploaded_at: ca_uploaded_at} = settings =
```
with this we can pass later in the `render(SoftwareUpdatesView, "user_settings.json", settings)` and assert that the output only contains what we expect

2024-02-02 14:28 UTC, nelsonkopliku approved these changes
LGTM

2024-02-02 14:32 UTC, nelsonkopliku approved these changes

2024-02-05 11:51 UTC, nelsonkopliku commented on test/trento_web/controllers/v1/software_updates_controller_test.exs
> +  import Mox
is mox actually needed here?

2024-02-05 15:54 UTC, jamie-suse commented on test/trento_web/controllers/v1/software_updates_controller_test.exs
> +  import Mox
Nope, good catch!

2024-02-06 08:56 UTC, merged