Add endpoint to clear SUMA credentials
trento-project/web pull request #2272
Opened 2024-02-07 14:16 UTC by jamie-suse

# Description

Adds an endpoint to clear user settings for SUSE Manager.

Endpoint is idempotent - server returns `200` status regardless if user settings have been previously saved or not.

## How was this tested?

Added unit tests.

2024-02-08 16:25 UTC, nelsonkopliku approved these changes

2024-02-08 16:52 UTC, jamie-suse commented
I can't approve my own Pull Request but LGTM :heart_eyes: :rocket:

2024-02-09 08:56 UTC, dottorblaster requested changes
Tiny change request then we can merge :+1:

2024-02-09 08:56 UTC, dottorblaster commented on lib/trento_web/controllers/v1/suma_credentials_controller.ex
> +    end
```suggestion
   :ok = SoftwareUpdates.clear_settings()
   send_resp(conn, :no_content, "")
```

You can just match that result, no need for the `with` :wink:

2024-02-09 09:48 UTC, dottorblaster approved these changes
LGTM

2024-02-09 09:49 UTC, merged