Cluster details updates
trento-project/web pull request #2328
Opened 2024-02-16 13:55 UTC by rtorrero

# Description

This PR adds some of the UI changes proposed by @jagabomb:

 - details button becomes a link
 - details content header changes from "Site details" to "Node details"
 - rounded bottom of tables 
 - top margins in the resources in the node details view
 - stop resources section should go under the site details section
 - stop resources section becomes a fixed section and when there are no stopped resources it shows a text saying "No resources to display"

See attached screenshots for more details:
![Captura desde 2024-02-16 13-49-53](https://github.com/trento-project/web/assets/2668401/a90ab341-0b62-4fb7-af9f-4fe3934d4c62)
![Captura desde 2024-02-16 13-49-32](https://github.com/trento-project/web/assets/2668401/9f4d76d0-ca50-46cd-8b5e-ac37e239f923)
![Captura desde 2024-02-16 13-49-46](https://github.com/trento-project/web/assets/2668401/1dc8a5c3-6b72-419a-99ff-ca0fb8ea26bb)

2024-02-19 07:55 UTC, arbulu89 reviewed
Hey @rtorrero 
Only one thing. With the rounded table thing, the header row shouldn't be rounded when there is an additional header on top of it.
Besides that, all of the table in the app are rounder now, and I don't think this was desired. We should have some rounder option as prop in the Table component I guess to make it variable.
What do you think @jagabomb ?

2024-02-19 08:21 UTC, jagabomb commented
> Hey @rtorrero Only one thing. With the rounded table thing, the header row shouldn't be rounded when there is an additional header on top of it. Besides that, all of the table in the app are rounder now, and I don't think this was desired. We should have some rounder option as prop in the Table component I guess to make it variable. What do you think @jagabomb ?

Well spotted @arbulu89, yeah only the top and bottom sections of the **Site Detail** component should be rounded. So in this case the, **Site Name** (NBG/WDF) would be the top part of the component with the top rounded corners. Then the grey **Table Header** (Hostname, Nameserver, etc) without any rounded corners. Followed by the **Table Description** with bottom rounded corners. This styling helps to make the **Sites Detail** nodes feel like single components.

2024-02-19 15:28 UTC, rtorrero commented
> > Hey @rtorrero Only one thing. With the rounded table thing, the header row shouldn't be rounded when there is an additional header on top of it. Besides that, all of the table in the app are rounder now, and I don't think this was desired. We should have some rounder option as prop in the Table component I guess to make it variable. What do you think @jagabomb ?
> 
> Well spotted @arbulu89, yeah only the top and bottom sections of the **Site Detail** component should be rounded. So in this case the, **Site Name** (NBG/WDF) would be the top part of the component with the top rounded corners. Then the grey **Table Header** (Hostname, Nameserver, etc) without any rounded corners. Followed by the **Table Description** with bottom rounded corners. This styling helps to make the **Sites Detail** nodes feel like single components.

once https://github.com/trento-project/web/pull/2337 is merged, I'll adjust this and re-request review :+1:

2024-02-19 15:34 UTC, EMaksy approved these changes
Nice, you survived the CSS war. 
LGTM!

2024-02-19 17:04 UTC, rtorrero commented
@jagabomb @arbulu89 seems to be good now: with header
![image](https://github.com/trento-project/web/assets/2668401/ca0e57b6-598f-4a8c-890f-e9e6505bc62e)

without header:
![image](https://github.com/trento-project/web/assets/2668401/7bbfc255-c6ff-4d2d-8c62-046d4734593b)

2024-02-20 07:48 UTC, arbulu89 requested changes
@rtorrero 
Looks good.
Please add a test to the `StoppedResources` view, for the 0 resources scenario.

2024-02-20 09:17 UTC, arbulu89 approved these changes
Please change the import.
We are fine to merge afterwards

2024-02-20 09:17 UTC, arbulu89 commented on assets/js/pages/ClusterDetails/StoppedResources.test.jsx
> +import { renderWithRouter } from '@lib/test-utils';
You don't need `renderWithRouter` use `render` coming from `@testing-library/react`
```
import { screen, render } from '@testing-library/react';
```

2024-02-20 13:21 UTC, merged