Openapi schemas no additional properties
trento-project/web pull request #2355
Opened 2024-02-21 12:07 UTC by CDimonaco

# Description

This PR aims to fix the properties of OpenApi Schemas.
This change involves the schemas, controllers and views.
Now our openapi schema is consistent with web responses.

Controller response views and broadcast views are differentiated, in order to achieve consistency on both the transports.

I introduced a new convention the `broadcast_` prefix in views means that the views are used **ONLY** in the broadcast of messages.

Remember to add the right labels to this PR.

Automated tests

2024-02-21 15:29 UTC, dottorblaster approved these changes
I really like the approach of creating dedicated view clauses for broadcasts :+1:

2024-02-22 08:25 UTC, arbulu89 requested changes
Hey @CDimonaco 
Great effort.
Unfortunately, there are many things wrong.
I think you have trusted too much in the current state of the schemas.
Many changes you did in the views are wrong, because you based them in the schema, but the schema itself is what it is wrong.
I think I have caught all  the things.
Let me know if you need more details.

As a nitpick:
The database and sapsystem view changes. The content we send in the controller and in the broadcast should be the same. It you want to keep the duplicated code, to be explicit, so be it, but with the same content

2024-02-22 08:25 UTC, arbulu89 commented on lib/trento_web/openapi/v1/schema/host.ex
> +        health: ResourceHealth,
Nitpick.
Not about this field.
I have checked a bit the code, and the value we could deprecate is the `deregistered_at`.
It is not used in the frontend anywhere.
So we could remove it in a potential, v2 version.
Anyway, it is not strictly about this PR. Up to you. If you don't do it, it is not a big deal.

2024-02-22 08:25 UTC, arbulu89 commented on lib/trento_web/views/v1/sap_system_view.ex
> +    |> Map.delete(:absent_at)
We shouldn't remove this field. It is used in the frontend.
The error must be that it is not defined in the schema.

2024-02-22 08:25 UTC, arbulu89 commented on lib/trento_web/views/v1/sap_system_view.ex
> +        database:
I think we could render inside this the `database.json` view.
After all, they have the exact same fields, both the database and instance (removing the `deregistered_at` is not a big deal, we don't use it in the frontend).
Anyway, if having it explicit makes sense to you, all good from my side, but they should have the same content

2024-02-22 08:25 UTC, arbulu89 commented on lib/trento_web/views/v1/sap_system_view.ex
> +    |> Map.delete(:absent_at)
We cannot remove the `absent_at`, it is used in the frontend.
And it would look like exactly as the broadcast

2024-02-22 08:25 UTC, arbulu89 commented on lib/trento_web/views/v1/sap_system_view.ex
> +  def render("broadcast_sap_system.json", %{
You can remove the `deregistered_at` from the broadcast as well

2024-02-22 08:25 UTC, arbulu89 commented on lib/trento_web/views/v2/cluster_view.ex
> +      Enum.map(sap_systems, &Map.take(&1, [:distributed, :filesystem_resource_based, :nodes]))
What is this for? to remove the `sid` field?
The sid cannot be removed, it is used in the frontend.
Yet again, most probably the schema is what it is wrong

2024-02-22 08:32 UTC, dottorblaster commented on lib/trento_web/views/v1/host_view.ex
> +    |> Map.delete(:selected_checks)
You're right, we take this and put it in the hosts slice as it is.

2024-02-22 08:33 UTC, CDimonaco commented
I took schema and tests for granted :eyes:

So, back to draft and we need to start back from schemas, good catch, fixing this things will give more confidence, but it's a real mess, we will learn a very valuable lesson in the end, I hope so :eyes:

Anyway some code duplication is completely on purpose, and if we want to avoid we need to rethink all the schemas because rn broadcasted info and controller one are very different

2024-02-22 08:46 UTC, nelsonkopliku commented on lib/trento_web/views/v1/host_view.ex
> +    |> Map.delete(:selected_checks)
Correct, both when first loading the `/hosts` api and when some event that gets projected changes the selected checks.

2024-02-22 09:48 UTC, arbulu89 approved these changes
Now it looks great @CDimonaco 
+1000

2024-02-22 10:36 UTC, merged