Extend error handling of `AvailableSoftwareUpdates` component
trento-project/web pull request #2538
Opened 2024-04-22 16:20 UTC by jamie-suse

# Description

This PR extends error handling for the `AvailableSoftwareUpdates` component.

When no SUSE Manager settings are saved, display the following to the user:

![image](https://github.com/trento-project/web/assets/113615552/ef6f4e26-e7c8-438a-9d3b-775c96d2658f)

If some SUSE Manager settings have already been saved, we enter the _loading_ state:

![image](https://github.com/trento-project/web/assets/113615552/83a30dcc-4fc0-4021-96c7-38aa1c890983)

If we get _any_ error response from SUSE Manager, we display it to the user as follows:

![image](https://github.com/trento-project/web/assets/113615552/4e490a3c-08bf-4ebf-ba14-706855ab77b9)

Finally, there is a catch-all _unknown_ state. Where if for some reason we receive a `2XX` response but there is no data in the response, we display the following:

![image](https://github.com/trento-project/web/assets/113615552/16fac67a-efb1-4ec5-8c64-9b400f072c1b)

## How was this tested?

Added unit tests for the new states

2024-04-22 16:21 UTC, jamie-suse commented
I need to update Storybook demos, but will do after feedback

2024-04-23 07:18 UTC, nelsonkopliku requested changes
Hey @jamie-suse, I guess there is something we need to address:

**In a host detail page, even if there are settings, the `Settings` CTA is shown**
How to reproduce:
- configure suma settings
- browse to any host detail (you should see what expected)
- refresh host detail page (you should see the CTA even though settings are available)

This is happening because we are selecting from a piece of state that gets populated only if we browse settings page.

If we want to rely on that piece of state we might want to load suma settings at application startup (I initially understood you would have relied on the result from `/api/v1/hosts/:host_id/software_updates`, but I actually prefer the other approach)

2024-04-23 07:27 UTC, jagabomb commented
@jamie-suse for the loading state can we remove the word, "_Loading..._" and just keep the preloading spinner. I think the space is small and the preloader should be enough to convey the loading state. Please see the attachment for reference,
<img width="1470" alt="Screenshot 2024-04-19 at 11 24 29" src="https://github.com/trento-project/web/assets/40714533/23166f8d-47e8-4a88-a8e2-5ad5153ce702">

2024-04-23 08:05 UTC, dottorblaster requested changes
Some changes to do but the overall design looks good, keep it up!

2024-04-23 08:40 UTC, jamie-suse commented on assets/js/pages/HostDetailsPage/HostDetailsPage.jsx
> +      softwareUpdatesSettingsSaved={softwareUpdatesConnectionSaved}
Hmm yeah same, any suggestions welcome

2024-04-23 14:29 UTC, dottorblaster approved these changes
Apart from what @nelsonkopliku mentioned, everything fine :+1:

2024-04-23 16:16 UTC, nelsonkopliku requested changes
Definitely a step forward, thanks @jamie-suse!

Back on the very initial feedback shared offline: I guess we're missing a loading state for the whole Available software updates section.

The API that tells us whether we have settings or not (`/api/v1/settings/suma_credentials`) might take a while to load and the ux transition feels a bit cumbersome: we show by default the section with the CTA which might get suddenly replaced by indicators.

In the attached gif I faked a 5s delay in the controller to give a sense of what I mean.
Besides this the endpoint we rely on might even fail, but I believe we can safely fallback to the  no-settings-available state in order to not add a failure option.

@jagabomb what do you think?
 
![loading-software-updates-section](https://github.com/trento-project/web/assets/8167114/7ff652e8-775c-4a7f-92ef-f312a7e0f5d3)

Besides this a tiny visual thing: the section with the CTA (when settings are not available) seems to need a bit of padding/margin adjustment

![image](https://github.com/trento-project/web/assets/8167114/ade3587d-1552-42be-851b-fe31ec3af8d4)

2024-04-24 08:19 UTC, jagabomb commented
Thanks for this @nelsonkopliku and @jamie-suse. I still wonder why we show the Available Software Updates (No Settings state) by default if a user has saved SUMA settings? Would it not be better to start with a **loading state** (refer to image below) just showing the **Available Patches** and **Upgradable Packages** sections as the default state, if we know you have **saved SUMA settings**. Basically switching between the two states above can be misleading to the user since they may believe the settings had not saved correctly.

<img width="1470" alt="Screenshot 2024-04-19 at 11 24 29" src="https://github.com/trento-project/web/assets/40714533/c4fb2acc-cf46-4df9-9fd2-3adec24bb50e">

2024-04-25 14:20 UTC, jagabomb commented
@jamie-suse As per our huddle review, can we please change the loading state for the Patches and Packages section to text saying just "Loading..." with not pre loader icon. Rationale is that the multiple pre loaders seems to be visually confusing.
<img width="1146" alt="Screenshot 2024-04-25 at 16 14 32" src="https://github.com/trento-project/web/assets/40714533/1ce6e826-b5f5-48e7-9920-b17ab646abea">

2024-04-26 07:51 UTC, nelsonkopliku approved these changes
LGTM

2024-04-26 08:20 UTC, jagabomb approved these changes
LGTM!

2024-04-26 08:47 UTC, merged