Add filters to Activity log page
trento-project/web pull request #2898
Opened 2024-08-14 10:20 UTC by balanza

# Description

Add filtering to the Activity log page

## Changes
* Allow the page to call the underlying API with needed params
* Mount filter by resource type
* Mount filter by date from
* Allow filters to be loaded from querystring
* refine `[Apply]` and `[Reset]` button sizes
* refine `<DateFilter>` input

## How was this tested?
E2E tests

2024-08-14 10:21 UTC, balanza commented
Depends on #2892 

Draft until it's merged

2024-08-14 10:45 UTC, balanza commented on assets/js/pages/ActivityLogPage/ActivityLogPage.jsx
> +  [...searchParams.entries()].reduce(
**TIL** being `searchParams` an instance of `URLSearchParams`, `searchParams.entries()` returns an `Iterator` object. Or better: an object that implements the `Iterator` interface.

When running on the browser (Chrome), `searchParams.entries().reduce` is fine as it returns an `Array` object (which implements `Iterator`), to mimic the behavior of `Object.entries`.

However, when running tests `searchParams.entries().reduce` is not defined, as Node implements [its own `Iterator` class](https://github.com/nodejs/node/blob/123693ccbf97df37f928a8ec3e39b85d5e719a7c/lib/internal/url.js#L217).

Thus the need to convert the iterator into an Array :shrug:

2024-08-14 10:59 UTC, gagandeepb reviewed
Thanks, looks great. I wonder if you want to address the below behavior in this PR ?

![image](https://github.com/user-attachments/assets/47569a24-15ec-4168-bb9d-e766147c388b)

2024-08-14 11:02 UTC, balanza commented
> Thanks, looks great. I wonder if you want to address the below behavior in this PR ?
> 
> ![image](https://private-user-images.githubusercontent.com/18139046/357785647-47569a24-15ec-4168-bb9d-e766147c388b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MzM0NzgsIm5iZiI6MTcyMzYzMzE3OCwicGF0aCI6Ii8xODEzOTA0Ni8zNTc3ODU2NDctNDc1NjlhMjQtMTVlYy00MTY4LWJiOWQtZTc2NjE0N2MzODhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDEwNTkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NTJkMWEyY2EyMjlkYThlNGRkYTkwOTYwNjA2M2UyMjM3OWUyMjc0YjRiNTI5YWZjZjc1ZWVkYTQ5YzcwZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3A0h9q-UddstZNEH8C-LcSzKn-A91cHCfB7WWxppJWg)

Good point. The current pagination is fake, I think we should not care now as we will implement it soon. 
Without proper pagination the feature won't be usable anyway, so I wouldn't bother for now.

2024-08-14 11:12 UTC, gagandeepb requested changes
When I want to see logs from 30 days ago, the cutoff date would be say `2024-07-15T...`, then this date should be passed to the `to_date` parameter, with `from_date` being `utc_now()`. IIUC, the usage here is flipped.

2024-08-14 12:14 UTC, balanza commented
> When I want to see logs from 30 days ago, the cutoff date would be say `2024-07-15T...`, then this date should be passed to the `to_date` parameter, with `from_date` being `utc_now()`. IIUC, the usage here is flipped.

Probably I misunderstood the meaning of `from_date` and `to_date`. The way I get it, is the chart below:
![image](https://github.com/user-attachments/assets/52c5cc3f-4b24-498b-b809-bcf9feab481a)

I created a branch with that use the `to_date` as you suggested: https://github.com/trento-project/web/tree/ui-activity-log-filter-alternate, we can compare the behaviour.

2024-08-15 15:08 UTC, balanza commented
There were some issues when converting dates back and forth from UTC to local time zones. They have been addressed in https://github.com/trento-project/web/pull/2898/commits/54e8be5031f86e7256a4957fac78d696c225214e.

Some notes about the modifications:
* the `data-fns-tz` dependency has been added
* helpers `fromZonedTime` and `toZonedTime` are used when needed.
* better formatting has been applied to rendered data items

We might want to move all time zone conversions to the `<DateFilter>` component to segregate the responsibility. That will require a review of the component API, I'll leave it for another PR.

2024-08-15 15:44 UTC, balanza commented
@gagandeepb in https://github.com/trento-project/web/pull/2898/commits/8801a4d55bb4ce778e2e086af136de3945d6efd4 I also added the `to_date` filter for cutting off entries older than a given date. I also change the labels as they may be more clear to users:
* _Filter older than_ for `from_date`
* _Filter newer than_ for `to_date`

We might consider adding some semantic validation (valid date range) in the future, but I think it is enough to have users use the feature now.

Tbh, I'm still of the idea that we won't need a _newer than_  filter, as the collection is sequential and the user will have to scroll and scan anyway. But I think we will understand better as soon as we start using the feature with relevant data.

2024-08-15 17:18 UTC, gagandeepb approved these changes
Thanks. It already looks much better! :smile:

2024-08-19 09:01 UTC, merged