Added Clear button to Filter component when one or more values are selected.
trento-project/web pull request #915
Opened 2022-10-19 13:24 UTC by jagabomb

# Description

This is a visual enhancement which helps users to be able to clear multiple values from the Filter component. In other words the user no longer needs to re-open the filter dropdown and deselect each option to clear the filter.

## How was this tested?

Visually in Chrome and Safari

![Trento Filter Clear Button](https://user-images.githubusercontent.com/40714533/196702563-ee495428-186d-47ca-be8b-62ce09ea45b8.gif)

2022-10-19 13:38 UTC, EMaksy reviewed
LGTM!

2022-10-20 08:48 UTC, dottorblaster requested changes
Sorry, I had the review pending from yesterday :D

2022-10-20 09:18 UTC, jagabomb commented on assets/js/components/Table/Filter.jsx
> +            onClick={() => onChange((value = []))}
@dottorblaster Thanks, I will make this change.

2022-10-20 10:30 UTC, dottorblaster approved these changes
LGTM

2022-10-20 11:46 UTC, arbulu89 approved these changes
@jagabomb It looks nice.
A pity that we cannot put the logic one next the other for this "depth" thing

2022-10-20 12:58 UTC, merged