Improve catalog container usability
trento-project/web pull request #968
Opened 2022-11-09 09:37 UTC by arbulu89

# Description
Make the `CatalogContainer` usage a bit more generic. This will help us to reuse this component in other places where the catalog data is queried from wanda.

## How was this tested?
I have added some new tests using the `axios-mock-adapter`. This helps us to test more thoroughly the real usage of data coming from wanda

2022-11-24 15:37 UTC, dottorblaster requested changes
Just some changes then we can merge

2022-11-25 07:24 UTC, arbulu89 commented on assets/js/state/index.js
> +    catalog_new: catalogNewReducer,
Yes, once we do the transition to the new wanda engine, we will remove all of this `new` suffixes and remove old catalog code.
PD: Damn camelCase, snake_case and all possible options XD

2022-11-25 07:27 UTC, arbulu89 commented on assets/js/state/index.js
> +    catalog_new: catalogNewReducer,
@dottorblaster would it make sense to start putting the reducers code in a `reducers` folder? within the `state` folder

2022-11-25 07:46 UTC, dottorblaster commented on assets/js/state/index.js
> +    catalog_new: catalogNewReducer,
> PD: Damn camelCase, snake_case and all possible options XD

also kebab-case! :smile: 

> would it make sense to start putting the reducers code in a reducers folder?

Maybe, but these are not proper reducers per-se, maybe a `slices` directory? Maybe it's better to have this on the radar but deferring it right now

2022-11-25 08:12 UTC, arbulu89 commented on assets/js/state/index.js
> +    catalog_new: catalogNewReducer,
@dottorblaster Forget about it. I have been reading redux guidlines, and they suggest to create folders by logical components. But we are really far from that concept.
We can discuss in the future if we want/can update the folders structure

2022-11-25 08:16 UTC, dottorblaster commented on assets/js/state/index.js
> +    catalog_new: catalogNewReducer,
Yeah we should totally revisit this @arbulu89, I'll create a tech debt to track this, good catch

2022-11-25 09:19 UTC, arbulu89 commented
Hey @dottorblaster ,
I have applied the requested changes, and even included some improvements to use the new `wanda` api code, so we have a centralized api usage.
I'm ommiting by now the `error/errorMessage` change if you don't mind. We already discussed offline the option to have some sort of `Boolean` selector, but we can include that afterwards

2022-11-25 09:50 UTC, dottorblaster approved these changes
> and even included some improvements to use the new wanda api code, so we have a centralized api usage

I forgot to tell you about that, you did the right thing!

2022-11-25 11:10 UTC, merged