Document SAP system aggregate
trento-project/web pull request #988
Opened 2022-11-16 08:57 UTC by arbulu89

Document SAP system aggregate code. I have included some additional documentation in the SAP application instance registering command, to explain how the application and database are associated.
This part of the code is a bit hidden, but I hope the new docs help a bit on that.

PD: We cannot put docs in the protocol code as it is a `defimpl`, that's why it goes in the register command, which at the end looks an appropriate place

2022-11-16 16:38 UTC, dottorblaster requested changes
Just some really tiny suggestions, awesome job man

2022-11-16 16:38 UTC, dottorblaster commented on lib/trento/domain/sap_system/sap_system.ex
> +  particular host. So the instance runs entirely in one host, but in the other hand
```suggestion
  particular host. So the instance runs entirely in one host, but on the other hand
```

2022-11-16 16:38 UTC, dottorblaster commented on lib/trento/domain/sap_system/sap_system.ex
> +  **The HANA database is the unique supported database type.**
```suggestion
  **The HANA database is the only supported database type.**
```

2022-11-16 16:38 UTC, dottorblaster commented on lib/trento/domain/sap_system/sap_system.ex
> +  A SAP instance can be understood as a single SAP workload installation running in a
```suggestion
  A SAP instance can be seen as a single SAP workload installation running in a
```

2022-11-16 16:38 UTC, dottorblaster commented on lib/trento/domain/sap_system/sap_system.ex
> +  that are working together in a System replication scenario.
```suggestion
  that are working together in a System Replication scenario.
```

2022-11-16 16:38 UTC, dottorblaster commented on lib/trento/domain/sap_system/sap_system.ex
> +  The SAP system registration process have some caveats, so let's see them in more details.
```suggestion
  The SAP system registration process has some caveats, so let's see them in more details.
```

2022-11-17 07:36 UTC, arbulu89 commented
Thanks @dottorblaster ,
All changed. All were good suggestions!

2022-11-17 07:51 UTC, dottorblaster approved these changes
LGTM

2022-11-17 13:13 UTC, fabriziosestito requested changes
Great work! Just a nitpick and then go!

2022-11-17 13:13 UTC, fabriziosestito commented on lib/trento/domain/sap_system/sap_system.ex
> +  by multiple instances altogether. This means that a SAP system aggregate stream can have
i would use state instead of stream

2022-11-17 13:34 UTC, arbulu89 commented on lib/trento/domain/sap_system/sap_system.ex
> +  by multiple instances altogether. This means that a SAP system aggregate stream can have
done!

2022-11-17 13:39 UTC, nelsonkopliku approved these changes
Gonna read this many times :stuck_out_tongue: 
Good job!

2022-11-18 11:30 UTC, merged